### ISSUE TITLE
Could not start the cluster, getting the following error. 

### ISSUE THREAD

**Issue by Baazigar007** [solarhess/kubernetes-minecraft-server#1]
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx    2 1000     1000          4096 Aug 23 15:42 /data'
curl: (6) Could not resolve host: launchermeta.mojang.com
[init] Resolved version given LATEST into 
[init] Resolving type given VANILLA
[init] Downloading minecraft_server..jar ...
curl: (6) Could not resolve host: launchermeta.mojang.com
[init] ERROR failed to obtain version manifest URL (6)

**Comment by xurizaemon** [comment]
```
$ host launchermeta.mojang.com
launchermeta.mojang.com is an alias for d1dulol58c5ch1.cloudfront.net.
d1dulol58c5ch1.cloudfront.net has address 65.9.132.19
```

That host does get DNS, which suggests that the pod started is unable to get DNS locally (might be an issue with kubernetes or the host machine). I don't see that hostname launchermeta.mojang.com in this repository's code at all. Suggest testing if similar pods have working in your local environment (and if they do, check if they have specific DNS config you'd need to apply to this service). I'm not a kubes expert at all FWIW. Good luck!

**Comment by Baazigar007** [comment]
Yeah, applying DNS config worked for me.

apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  upstreamNameservers: |
    ["8.8.8.8"]
